In [5]:
import pandas as pd

In [6]:
df = pd.read_csv('Titanic.csv')
type(df)

pandas.DataFrame

In [7]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [41]:
print(df.head())
print(df.tail())

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0         0       3    male  22.0      1      0   7.2500   NaN        S
1         1       1  female  38.0      1      0  71.2833   C85        C
2         1       3  female  26.0      0      0   7.9250   NaN        S
3         1       1  female  35.0      1      0  53.1000  C123        S
4         0       3    male  35.0      0      0   8.0500   NaN        S
     Survived  Pclass     Sex   Age  SibSp  Parch   Fare Cabin Embarked
886         0       2    male  27.0      0      0  13.00   NaN        S
887         1       1  female  19.0      0      0  30.00   B42        S
888         0       3  female   NaN      1      2  23.45   NaN        S
889         1       1    male  26.0      0      0  30.00  C148        C
890         0       3    male  32.0      0      0   7.75   NaN        Q

In [38]:
def Drop_unnecessary_features(df, cols_to_drop):
    df = df.drop(columns=cols_to_drop, errors='ignore')
    return df


cols_to_drop = ['PassengerId', 'Name', 'Ticket']


df = Drop_unnecessary_features(df, cols_to_drop)


df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0         0       3    male  22.0      1      0   7.2500   NaN        S
1         1       1  female  38.0      1      0  71.2833   C85        C
2         1       3  female  26.0      0      0   7.9250   NaN        S
3         1       1  female  35.0      1      0  53.1000  C123        S
4         0       3    male  35.0      0      0   8.0500   NaN        S

In [ ]:
def Check_data_type(df):
    report = pd.DataFrame({
        'Datatype': df.dtypes,
        'Unique_Values': df.nunique()
    })
   
    return report.T

In [40]:
Check_data_type(df)

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked
Datatype,int64,int64,str,float64,int64,int64,float64,str,str
Unique_Values,2,3,2,88,7,7,248,147,3

In [49]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Sex       891 non-null    str
 3   Age       714 non-null    float64
 4   SibSp     891 non-null    int64
 5   Parch     891 non-null    int64
 6   Fare      891 non-null    float64
 7   Cabin     204 non-null    str
 8   Embarked  889 non-null    str
dtypes: float64(2), int64(4), str(3)
memory usage: 62.8 KB

In [51]:
cat_cols = ['Survived', "Pclass", "Sex", "SibSp", "Parch", "Embarked"]
df[cat_cols] = df[cat_cols].astype("category")
dtypes = df.dtypes
nunique = df.nunique()
pd.DataFrame({"dtypes": dtypes, "nunique": nunique}).T

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked
dtypes,category,category,category,float64,category,category,float64,str,category
nunique,2,3,2,88,7,7,248,147,3

In [52]:
def get_type_info(df):
    return pd.DataFrame({"dtypes": df.dtypes, "nunique": df.nunique()}).T
get_type_info(df)

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked
dtypes,category,category,category,float64,category,category,float64,str,category
nunique,2,3,2,88,7,7,248,147,3

In [57]:
df.select_dtypes("category")

    Survived Pclass     Sex SibSp Parch Embarked
0          0      3    male     1     0        S
1          1      1  female     1     0        C
2          1      3  female     0     0        S
3          1      1  female     1     0        S
4          0      3    male     0     0        S
..       ...    ...     ...   ...   ...      ...
886        0      2    male     0     0        S
887        1      1  female     0     0        S
888        0      3  female     1     2        S
889        1      1    male     0     0        C
890        0      3    male     0     0        Q

[891 rows x 6 columns]

In [63]:

def check_outliers_iqr(df):
    num_col = df.select_dtypes("number").columns
    
    for col in num_col:
        Q1 = df[col].quantile(0.25)
        Q3 = df[col].quantile(0.75)
        IQR = Q3 - Q1
        lower_fence = Q1 - 1.5 * IQR
        upper_fence = Q3 + 1.5 * IQR
        
        print(f"Column: {col}")
        print(f"Q1: {Q1}, Q3: {Q3}")
        print(f"IQR: {IQR}")
        print(f"Bounds: ({lower_fence}, {upper_fence})")
        print("-" * 30)

In [62]:
check_outliers_iqr(df)

Column: Age
Q1: 20.125, Q3: 38.0
IQR: 17.875
Bounds: (-6.6875, 64.8125)
------------------------------
Column: Fare
Q1: 7.9104, Q3: 31.0
IQR: 23.0896
Bounds: (-26.724, 65.6344)
------------------------------