In [1]:
import pandas as pd

In [7]:
df = pd.read_csv("C:/Users/11/OneDrive - Future University in Egypt/Desktop/DEPI/CA-R5-S2S2-AI/src/DA/Session-3&4/code/titanic.csv")

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 22: invalid start byte

In [8]:
df.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

In [9]:
df.drop(["PassengerId", "Name", "Ticket"], axis=1, inplace=True)

In [10]:
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0         0       3    male  22.0      1      0   7.2500   NaN        S
1         1       1  female  38.0      1      0  71.2833   C85        C
2         1       3  female  26.0      0      0   7.9250   NaN        S
3         1       1  female  35.0      1      0  53.1000  C123        S
4         0       3    male  35.0      0      0   8.0500   NaN        S

In [17]:
DROP_COLUMNS = ["PassengerId", "Name", "Ticket"]

In [22]:
from config import DROP_COLUMNS
def drop_cols(df: pd.DataFrame, cols: list[str])-> pd.DataFrame:
    """
    Drop specific cols from df
    
    
    
    """
    return df.drop(columns=cols)

# drop cols

In [19]:
df = drop_cols(df, DROP_COLUMNS)

In [21]:
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0         0       3    male  22.0      1      0   7.2500   NaN        S
1         1       1  female  38.0      1      0  71.2833   C85        C
2         1       3  female  26.0      0      0   7.9250   NaN        S
3         1       1  female  35.0      1      0  53.1000  C123        S
4         0       3    male  35.0      0      0   8.0500   NaN        S

# check data types

In [ ]:
class student:
    
    def __init__(self, name) -> None:
        self._name = name
    @property
    def name(self):
        return self._name
    name.setter
    def name(self, value):
        return self._name = value

In [26]:
s1 = student("George")
s1.name

'George'

In [30]:
dtypes = df.dtypes
n_uniq = df.nunique()
pd.DataFrame({"Dtypes :":dtypes, "Num_Unique": n_uniq }).T

           Survived Pclass  Sex      Age  SibSp  Parch     Fare Cabin Embarked
Dtypes :      int64  int64  str  float64  int64  int64  float64   str      str
Num_Unique        2      3    2       88      7      7      248   147        3

In [33]:
def get_chk_dtype(df: pd.DataFrame)-> pd.DataFrame:
    return pd.DataFrame({"Dtypes :":df.dtypes, "Num_Unique": df.nunique() }).T

In [34]:
get_chk_dtype(df)

           Survived Pclass  Sex      Age  SibSp  Parch     Fare Cabin Embarked
Dtypes :      int64  int64  str  float64  int64  int64  float64   str      str
Num_Unique        2      3    2       88      7      7      248   147        3

In [37]:
from ps import get_chk_dtype
get_chk_dtype(df)

           Survived Pclass  Sex      Age  SibSp  Parch     Fare Cabin Embarked
Dtypes :      int64  int64  str  float64  int64  int64  float64   str      str
Num_Unique        2      3    2       88      7      7      248   147        3

In [42]:
cols = ['Pclass', 'Survived','SibSp','Sex','Parch','Embarked']
df[cols] = df[cols].astype('category')
pd.DataFrame(df.dtypes).T

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked
0,category,category,category,float64,category,category,float64,str,category

In [45]:
df.shape[0]

891

In [46]:
null =  df.isnull().sum()
ratio = null/ df.shape[0]
pd.DataFrame({"nulls_sum": null, "Ratio ": ratio}).T

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked
nulls_sum,0.0,0.0,0.0,177.000000,0.0,0.0,0.0,687.000000,2.000000
Ratio,0.0,0.0,0.0,0.198653,0.0,0.0,0.0,0.771044,0.002245

In [47]:
df = df.dropna(subset=['Embarked'])

In [48]:
df = df.drop("Cabin",axis = 1)

In [69]:
mean = df['Age'].mean()
print(mean)
print("="*20)
print(df['Age'].median())
# print(median)
df['Age'] = df['Age'].fillna(df['Age'].median())

29.64209269662921
====================
28.0

In [70]:
null =  df.isnull().sum()
ratio = null/ df.shape[0]
pd.DataFrame({"nulls_sum": null, "Ratio ": ratio}).T

           Survived  Pclass  Sex  Age  SibSp  Parch  Fare  Embarked
nulls_sum       0.0     0.0  0.0  0.0    0.0    0.0   0.0       0.0
Ratio           0.0     0.0  0.0  0.0    0.0    0.0   0.0       0.0

In [62]:
df.describe()

              Age        Fare
count  712.000000  889.000000
mean    29.642093   32.096681
std     14.492933   49.697504
min      0.420000    0.000000
25%     20.000000    7.895800
50%     28.000000   14.454200
75%     38.000000   31.000000
max     80.000000  512.329200

In [65]:
# num_cols = df.select_dtypes("number").columns
num_cols = ['Age', 'Fare']