## numpy

In [10]:
import numpy as np
def convert_dtype(arr , dtype):
    try:
        arr = np.asarray(arr)
        return arr.astype(dtype)
    except TypeError as r:
        raise TypeError(f"Invalid target data type {dtype}") from r
    except ValueError as r:
            raise ValueError(f"can not convert to {dtype}") from r
    
lst = [1.5 , 2.9 , 3.1 ]
convert_dtype(lst , int )

array([1, 2, 3])

In [19]:
def check_dtype(arr , dtype):
    if not isinstance(arr , np.ndarray):
        print("input must be a numpy")
    dtype = np.dtype(dtype)
    return arr.dtype == dtype

In [ ]:
lst = [1 , 2 , 3 ]
check_dtype(lst , int )

In [21]:
mat = np.full((3,4),5)
mat

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [30]:
def init_array(shape , value=0):
    return np.full(shape,value)
zeros = init_array((3,4))
print(zeros)

ones = init_array((3,4),1)
print("\n",ones)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

 [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]

In [47]:
def init_weights(n_feature, method = "zeros", seed =None):
    if not isinstance(n_feature, int):
        raise TypeError(f"{n_feature} must be an integer")
    if n_feature <= 0 :
        raise TypeError(f"{n_feature} must be gretar than zero")
    if method == "zeros":
        return np.zeros(n_feature)
    if method == "random":
        if seed is not None:
            return np.random.randn(n_feature) 
    raise  ValueError(f"un support the method type{method}")
print(init_weights(4,"random",42))
print(init_weights(4,"zeros"))
# print(init_weights(4.1,"zeros"))

[-0.80358246  0.39299477  0.10164413 -0.85013881]
[0. 0. 0. 0.]

In [53]:
i = np.identity(3,dtype="int")
i

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [54]:
np.random.random((3,3))

array([[0.4051966 , 0.21368646, 0.24965053],
       [0.02106547, 0.6869953 , 0.26080063],
       [0.29488334, 0.13575872, 0.57177327]])

In [55]:
np.random.randint(0,11,(5,5))

array([[ 7,  3,  6,  1,  1],
       [ 1,  6,  9,  4,  8],
       [ 8,  6, 10,  6,  0],
       [ 5,  3,  3,  7,  8],
       [ 2,  1,  2,  8,  1]], dtype=int32)

In [56]:
names = ["Osama","Mohammed","Essmat"]
np.random.choice(names,size=(5,5))

array([['Essmat', 'Essmat', 'Osama', 'Osama', 'Osama'],
       ['Essmat', 'Osama', 'Osama', 'Osama', 'Osama'],
       ['Mohammed', 'Mohammed', 'Mohammed', 'Osama', 'Mohammed'],
       ['Osama', 'Osama', 'Essmat', 'Essmat', 'Osama'],
       ['Mohammed', 'Essmat', 'Mohammed', 'Mohammed', 'Osama']],
      dtype='<U8')

In [ ]:
mat1= np.ones((3,4))
mat1
mat2= np.zeros((3,4))
mat2
np.savez('file_da.npz',one_mat=mat1 ,zeros_mat =mat2 )

In [64]:
with np.load('file_da.npz') as file:
    mat1 = file['one_mat']
    mat2 = file['zeros_mat']

mat2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [68]:
m1 = np.array([[1,2,3],[0,0,0]])
m2 = np.array([[4,5,6],[1,1,1]])
neu_mat = np.vstack((m1 , m2))
print(neu_mat)
neu_mat = np.hstack((m1 , m2))
neu_mat

[[1 2 3]
 [0 0 0]
 [4 5 6]
 [1 1 1]]

array([[1, 2, 3, 4, 5, 6],
       [0, 0, 0, 1, 1, 1]])

In [72]:
v = np.array((1,2,3,4,5,0))
np.any(v>=1)
np.all(v>=1)

np.False_

In [75]:
v1 = np.array((1,2,3,4,5,0))
v2 = np.array((2,3,0,1,5,1))
np.allclose(v1,v2,atol=1)
np.isclose(v1,v2,atol=1)

array([ True,  True, False, False,  True,  True])

In [ ]:
v1 = np.array((1,2,3,4,5,0))
condition = v1 >=4
v1[condition]= -1
print(v1)

[ 1  2  3 -1 -1  0]

In [78]:
v1 = np.array((1,2,3,4,5,0))
condition = v1 >=4
new_arr = np.where(condition, -1, v1)
new_arr

array([ 1,  2,  3, -1, -1,  0])

In [80]:
v1 = np.array((1,2,3,4,5,0))
v2 = np.array((1,2,3,4,5,0))

c = 2
summation = v1 +v2
multiplication = v1 * v2
print(summation)
print(multiplication)

[ 2  4  6  8 10  0]
[ 1  4  9 16 25  0]

## Pandas

In [ ]:
pip install pandas

In [83]:
import pandas as pd

In [87]:
s = pd.Series([1,2,3,4,5] , index=["A","B","C","D","E"])
s

A    1
B    2
C    3
D    4
E    5
dtype: int64

In [96]:
data =[[1,222,"abc"],[2,333,"bbb"],[3,444,"ccc"],[4,555,"fff"]]
pf = pd.DataFrame(data,columns=['col1','col2','col3'])

pf = pd.DataFrame(
    [[1,222,"abc"],[2,333,"bbb"],[3,444,"ccc"],[4,555,"fff"]])
display(pf)

   0    1    2
0  1  222  abc
1  2  333  bbb
2  3  444  ccc
3  4  555  fff

In [100]:
pf.dtypes

0    int64
1    int64
2      str
dtype: object

In [114]:
data = [[1,444,"abc"],
        [2,555,"def"],
        [3,666,"ghi"],
        [4,444,"xyz"]]

data = {'col1':[1,2,3,4],
        'col2':[444,555,666,444],
        'col3':['abc','def','ghi','xyz']}
df = pd.DataFrame(data)
df
df['col3'].dtype

In [116]:
df['col1'] = df['col1'].astype('category')
df.dtypes

col1    category
col2       int64
col3         str
dtype: object

In [117]:
df.describe()

             col2
count    4.000000
mean   527.250000
std    106.274409
min    444.000000
25%    444.000000
50%    499.500000
75%    582.750000
max    666.000000

In [127]:
df['col2'].unique()
df['col2'].sum()
df['col1'].info()
df['col1'].value_counts()

<class 'pandas.Series'>
RangeIndex: 4 entries, 0 to 3
Series name: col1
Non-Null Count  Dtype
--------------  -----
4 non-null      category
dtypes: category(1)
memory usage: 168.0 bytes

col1
1    1
2    1
3    1
4    1
Name: count, dtype: int64